# Generated by Django 5.0.4 on 2024-05-14 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=300, null=True)),
                ('gia', models.IntegerField()),
                ('hinh', models.ImageField(blank=True, null=True, upload_to='')),
                ('khuyen_mai', models.BooleanField(default=False)),
                ('gia_km', models.IntegerField(blank=True, null=True)),
                ('mo_ta', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dat', models.DateTimeField(auto_now_add=True)),
                ('ten', models.CharField(max_length=300, null=True)),
                ('hoan_thanh', models.BooleanField(default=False, null=True)),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='DiaChiGiaoHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thanh_pho', models.CharField(max_length=300, null=True)),
                ('quan', models.CharField(max_length=300, null=True)),
                ('dia_chi', models.CharField(max_length=300, null=True)),
                ('sdt', models.CharField(max_length=300, null=True)),
                ('ngay_giao', models.DateTimeField(auto_now_add=True)),
                ('don_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.donhang')),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='MucDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(blank=True, default=0, null=True)),
                ('ngay_them', models.DateTimeField(auto_now_add=True)),
                ('don_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.donhang')),
                ('san_pham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sanpham')),
            ],
        ),
        migrations.AddField(
            model_name='sanpham',
            name='the_loai',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.theloai'),
        ),
    ]
