# Generated by Django 5.0.4 on 2024-05-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mucdonhang',
            name='so_luong',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
