# Generated by Django 5.0.4 on 2024-05-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_mucdonhang_so_luong'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonHang',
            new_name='GioHang',
        ),
        migrations.RenameModel(
            old_name='MucDonHang',
            new_name='MucGioHang',
        ),
        migrations.RenameField(
            model_name='diachigiaohang',
            old_name='don_hang',
            new_name='gio_hang',
        ),
        migrations.RenameField(
            model_name='mucgiohang',
            old_name='don_hang',
            new_name='gio_hang',
        ),
    ]
