# Generated by Django 5.0.4 on 2024-05-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sanpham_kich_thuoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='kich_thuoc',
        ),
        migrations.AddField(
            model_name='mucgiohang',
            name='kich_thuoc',
            field=models.IntegerField(default=37, max_length=10),
        ),
    ]
