# Generated by Django 5.0.4 on 2024-05-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_diachigiaohang_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='diachigiaohang',
            name='ten_nguoi_nhan',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
