# Generated by Django 5.0.4 on 2024-05-26 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_diachigiaohang_ten_nguoi_nhan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mucgiohang',
            name='kich_thuoc',
            field=models.IntegerField(default=37),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(blank=True, max_length=300, null=True)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('sdt', models.CharField(blank=True, max_length=20, null=True)),
                ('hinh', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
                ('khach_hang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
