# Generated by Django 5.0.4 on 2024-05-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_mucgiohang_kich_thuoc_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hinh',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
