# Generated by Django 5.0.4 on 2024-05-26 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_profile_ho_ten_alter_profile_sdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ngay_sinh',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
