# Generated by Django 5.0.4 on 2024-05-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_diachigiaohang_gio_hang'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='hinh_phu_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='hinh_phu_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='hinh_phu_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='hinh_phu_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
