# Generated by Django 5.0.4 on 2024-05-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_sanpham_hinh_phu_1_sanpham_hinh_phu_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='mo_ta',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
